INSERT INTO public.currency (code, name, country)
VALUES
  ('aed', 'United Arab Emirates Dirham', 'United Arab Emirates (The)'),
  ('afn', 'Afghan Afghani', 'Afghanistan'),
  ('all', 'Albanian Lek', 'Albania'),
  ('amd', 'Armenian Dram', 'Armenia'),
  ('ang', 'Netherlands Antillean Gulden', 'Sint Maarten (Dutch Part)'),
  ('aoa', 'Angolan Kwanza', 'Angola'),
  ('ars', 'Argentine Peso', 'Argentina'),
  ('aud', 'Australian Dollar', 'Tuvalu'),
  ('awg', 'Aruban Florin', 'Aruba'),
  ('azn', 'Azerbaijani Manat', 'Azerbaijan'),
  ('bam', 'Bosnia and Herzegovina Convertible Mark', 'Bosnia And Herzegovina'),
  ('bbd', 'Barbadian Dollar', 'Barbados'),
  ('bdt', 'Bangladeshi Taka', 'Bangladesh'),
  ('bgn', 'Bulgarian Lev', 'Bulgaria'),
  ('bhd', 'Bahraini Dinar', 'Bahrain'),
  ('bif', 'Burundian Franc', 'Burundi'),
  ('bmd', 'Bermudian Dollar', 'Bermuda'),
  ('bnd', 'Brunei Dollar', 'Brunei Darussalam'),
  ('bob', 'Bolivian Boliviano', 'Bolivia (Plurinational State Of)'),
  ('brl', 'Brazilian Real', 'Brazil'),
  ('bsd', 'Bahamian Dollar', 'Bahamas (The)'),
  ('btn', 'Bhutanese Ngultrum', 'Bhutan'),
  ('bwp', 'Botswana Pula', 'Botswana'),
  ('byn', 'Belarusian Ruble', 'Belarus'),
  ('bzd', 'Belize Dollar', 'Belize'),
  ('cad', 'Canadian Dollar', 'Canada'),
  ('cdf', 'Congolese Franc', 'Congo (The Democratic Republic Of The)'),
  ('chf', 'Swiss Franc', 'Switzerland'),
  ('clp', 'Chilean Peso', 'Chile'),
  ('cny', 'Chinese Renminbi Yuan', 'China'),
  ('cop', 'Colombian Peso', 'Colombia'),
  ('crc', 'Costa Rican Colón', 'Costa Rica'),
  ('cuc', 'Cuban Convertible Peso', 'Cuba'),
  ('cup', 'Cuban Peso', 'Cuba'),
  ('cve', 'Cape Verdean Escudo', 'Cabo Verde'),
  ('czk', 'Czech Koruna', 'Czechia'),
  ('djf', 'Djiboutian Franc', 'Djibouti'),
  ('dkk', 'Danish Krone', 'Greenland'),
  ('dop', 'Dominican Peso', 'Dominican Republic (The)'),
  ('dzd', 'Algerian Dinar', 'Algeria'),
  ('egp', 'Egyptian Pound', 'Egypt'),
  ('ern', 'Eritrean Nakfa', 'Eritrea'),
  ('etb', 'Ethiopian Birr', 'Ethiopia'),
  ('eur', 'Euro', 'Eurozone'),
  ('fjd', 'Fijian Dollar', 'Fiji'),
  ('fkp', 'Falkland Pound', 'Falkland Islands (The) [Malvinas]'),
  ('gbp', 'British Pound', 'United Kingdom Of Great Britain And Northern Ireland (The)'),
  ('gel', 'Georgian Lari', 'Georgia'),
  ('ghs', 'Ghanaian Cedi', 'Ghana'),
  ('gip', 'Gibraltar Pound', 'Gibraltar'),
  ('gmd', 'Gambian Dalasi', 'Gambia (The)'),
  ('gnf', 'Guinean Franc', 'Guinea'),
  ('gtq', 'Guatemalan Quetzal', 'Guatemala'),
  ('gyd', 'Guyanese Dollar', 'Guyana'),
  ('hkd', 'Hong Kong Dollar', 'Hong Kong'),
  ('hnl', 'Honduran Lempira', 'Honduras'),
  ('htg', 'Haitian Gourde', 'Haiti'),
  ('huf', 'Hungarian Forint', 'Hungary'),
  ('idr', 'Indonesian Rupiah', 'Indonesia'),
  ('ils', 'Israeli New Sheqel', 'Israel'),
  ('inr', 'Indian Rupee', 'India'),
  ('iqd', 'Iraqi Dinar', 'Iraq'),
  ('irr', 'Iranian Rial', 'Iran (Islamic Republic Of)'),
  ('isk', 'Icelandic Króna', 'Iceland'),
  ('jmd', 'Jamaican Dollar', 'Jamaica'),
  ('jod', 'Jordanian Dinar', 'Jordan'),
  ('jpy', 'Japanese Yen', 'Japan'),
  ('kes', 'Kenyan Shilling', 'Kenya'),
  ('kgs', 'Kyrgyzstani Som', 'Kyrgyzstan'),
  ('khr', 'Cambodian Riel', 'Cambodia'),
  ('kmf', 'Comorian Franc', 'Comoros (The)'),
  ('kpw', 'North Korean Won', 'Korea (The Democratic People''s Republic Of)'),
  ('krw', 'South Korean Won', 'Korea (The Republic Of)'),
  ('kwd', 'Kuwaiti Dinar', 'Kuwait'),
  ('kyd', 'Cayman Islands Dollar', 'Cayman Islands (The)'),
  ('kzt', 'Kazakhstani Tenge', 'Kazakhstan'),
  ('lak', 'Lao Kip', 'Lao People''s Democratic Republic (The)'),
  ('lbp', 'Lebanese Pound', 'Lebanon'),
  ('lkr', 'Sri Lankan Rupee', 'Sri Lanka'),
  ('lrd', 'Liberian Dollar', 'Liberia'),
  ('lsl', 'Lesotho Loti', 'Lesotho'),
  ('lyd', 'Libyan Dinar', 'Libya'),
  ('mad', 'Moroccan Dirham', 'Western Sahara'),
  ('mdl', 'Moldovan Leu', 'Moldova (The Republic Of)'),
  ('mga', 'Malagasy Ariary', 'Madagascar'),
  ('mkd', 'Macedonian Denar', 'North Macedonia'),
  ('mmk', 'Myanmar Kyat', 'Myanmar'),
  ('mnt', 'Mongolian Tögrög', 'Mongolia'),
  ('mop', 'Macanese Pataca', 'Macao'),
  ('mru', 'Mauritanian Ouguiya', 'Mauritania'),
  ('mur', 'Mauritian Rupee', 'Mauritius'),
  ('mvr', 'Maldivian Rufiyaa', 'Maldives'),
  ('mwk', 'Malawian Kwacha', 'Malawi'),
  ('mxn', 'Mexican Peso', 'Mexico'),
  ('myr', 'Malaysian Ringgit', 'Malaysia'),
  ('mzn', 'Mozambican Metical', 'Mozambique'),
  ('nad', 'Namibian Dollar', 'Namibia'),
  ('ngn', 'Nigerian Naira', 'Nigeria'),
  ('nio', 'Nicaraguan Córdoba', 'Nicaragua'),
  ('nok', 'Norwegian Krone', 'Svalbard And Jan Mayen'),
  ('npr', 'Nepalese Rupee', 'Nepal'),
  ('nzd', 'New Zealand Dollar', 'Tokelau'),
  ('omr', 'Omani Rial', 'Oman'),
  ('pab', 'Panamanian Balboa', 'Panama'),
  ('pen', 'Peruvian Sol', 'Peru'),
  ('pgk', 'Papua New Guinean Kina', 'Papua New Guinea'),
  ('php', 'Philippine Peso', 'Philippines (The)'),
  ('pkr', 'Pakistani Rupee', 'Pakistan'),
  ('pln', 'Polish Złoty', 'Poland'),
  ('pyg', 'Paraguayan Guaraní', 'Paraguay'),
  ('qar', 'Qatari Riyal', 'Qatar'),
  ('ron', 'Romanian Leu', 'Romania'),
  ('rsd', 'Serbian Dinar', 'Serbia'),
  ('rub', 'Russian Ruble', 'Russian Federation (The)'),
  ('rwf', 'Rwandan Franc', 'Rwanda'),
  ('sar', 'Saudi Riyal', 'Saudi Arabia'),
  ('sbd', 'Solomon Islands Dollar', 'Solomon Islands'),
  ('scr', 'Seychellois Rupee', 'Seychelles'),
  ('sdg', 'Sudanese Pound', 'Sudan (The)'),
  ('sek', 'Swedish Krona', 'Sweden'),
  ('sgd', 'Singapore Dollar', 'Singapore'),
  ('shp', 'Saint Helenian Pound', 'Saint Helena, Ascension And Tristan Da Cunha'),
  ('sle', 'New Leone', 'Sierra Leone'),
  ('sos', 'Somali Shilling', 'Somalia'),
  ('srd', 'Surinamese Dollar', 'Suriname'),
  ('ssp', 'South Sudanese Pound', 'South Sudan'),
  ('stn', 'São Tomé and Príncipe Second Dobra', 'Sao Tome And Principe'),
  ('svc', 'Salvadoran Colón', 'El Salvador'),
  ('syp', 'Syrian Pound', 'Syrian Arab Republic'),
  ('szl', 'Swazi Lilangeni', 'Eswatini'),
  ('thb', 'Thai Baht', 'Thailand'),
  ('tjs', 'Tajikistani Somoni', 'Tajikistan'),
  ('tmt', 'Turkmenistani Manat', 'Turkmenistan'),
  ('tnd', 'Tunisian Dinar', 'Tunisia'),
  ('top', 'Tongan Paʻanga', 'Tonga'),
  ('try', 'Turkish Lira', 'Turkey'),
  ('ttd', 'Trinidad and Tobago Dollar', 'Trinidad And Tobago'),
  ('twd', 'New Taiwan Dollar', 'Taiwan (Province Of China)'),
  ('tzs', 'Tanzanian Shilling', 'Tanzania, United Republic Of'),
  ('uah', 'Ukrainian Hryvnia', 'Ukraine'),
  ('ugx', 'Ugandan Shilling', 'Uganda'),
  ('usd', 'United States Dollar', 'United States Of America'),
  ('uyu', 'Uruguayan Peso', 'Uruguay'),
  ('uzs', 'Uzbekistan Som', 'Uzbekistan'),
  ('veb', 'Venezuelan Bolívar Soberano', 'Venezuela (Bolivarian Republic Of)'),
  ('vnd', 'Vietnamese Đồng', 'Viet Nam'),
  ('vuv', 'Vanuatu Vatu', 'Vanuatu'),
  ('wst', 'Samoan Tala', 'Samoa'),
  ('xaf', 'Central African Cfa Franc', 'Gabon'),
  ('xcd', 'East Caribbean Dollar', 'Saint Vincent And The Grenadines'),
  ('xof', 'West African Cfa Franc', 'Togo'),
  ('xpf', 'Cfp Franc', 'Wallis And Futuna'),
  ('yer', 'Yemeni Rial', 'Yemen'),
  ('zar', 'South African Rand', 'South Africa'),
  ('zmw', 'Zambian Kwacha', 'Zambia');