create table "public"."institution_connection" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "institution_id" character varying not null,
    "connection_id" character varying,
    "provider_id" bigint not null,
    "user_id" uuid not null
);


CREATE UNIQUE INDEX institution_connection_id_key ON public.institution_connection USING btree (id);

CREATE UNIQUE INDEX institution_connection_pkey ON public.institution_connection USING btree (id);

alter table "public"."institution_connection" add constraint "institution_connection_pkey" PRIMARY KEY using index "institution_connection_pkey";

alter table "public"."institution_connection" add constraint "institution_connection_id_key" UNIQUE using index "institution_connection_id_key";

alter table "public"."institution_connection" add constraint "institution_connection_institution_fkey" FOREIGN KEY (institution_id, provider_id) REFERENCES institution(institution_id, provider_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."institution_connection" validate constraint "institution_connection_institution_fkey";

alter table "public"."institution_connection" add constraint "institution_connection_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."institution_connection" validate constraint "institution_connection_user_id_fkey";

grant delete on table "public"."institution_connection" to "anon";

grant insert on table "public"."institution_connection" to "anon";

grant references on table "public"."institution_connection" to "anon";

grant select on table "public"."institution_connection" to "anon";

grant trigger on table "public"."institution_connection" to "anon";

grant truncate on table "public"."institution_connection" to "anon";

grant update on table "public"."institution_connection" to "anon";

grant delete on table "public"."institution_connection" to "authenticated";

grant insert on table "public"."institution_connection" to "authenticated";

grant references on table "public"."institution_connection" to "authenticated";

grant select on table "public"."institution_connection" to "authenticated";

grant trigger on table "public"."institution_connection" to "authenticated";

grant truncate on table "public"."institution_connection" to "authenticated";

grant update on table "public"."institution_connection" to "authenticated";

grant delete on table "public"."institution_connection" to "service_role";

grant insert on table "public"."institution_connection" to "service_role";

grant references on table "public"."institution_connection" to "service_role";

grant select on table "public"."institution_connection" to "service_role";

grant trigger on table "public"."institution_connection" to "service_role";

grant truncate on table "public"."institution_connection" to "service_role";

grant update on table "public"."institution_connection" to "service_role";


