alter table "public"."institution" drop constraint "institution_pkey";

drop index if exists "public"."institution_pkey";

alter table "public"."institution" drop column "institution_id";

alter table "public"."institution" add column "id" bigint generated by default as identity not null;

alter table "public"."institution" add column "provider_institution_id" character varying not null;

CREATE UNIQUE INDEX institution_id_key ON public.institution USING btree (id);

CREATE UNIQUE INDEX institution_pkey ON public.institution USING btree (id);

alter table "public"."institution" add constraint "institution_pkey" PRIMARY KEY using index "institution_pkey";

alter table "public"."institution" add constraint "institution_id_key" UNIQUE using index "institution_id_key";


