create table "public"."transaction_category" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "display_name" text not null,
    "emoji" text not null
);


alter table "public"."transaction_category" enable row level security;

CREATE UNIQUE INDEX transaction_category_pkey ON public.transaction_category USING btree (id);

alter table "public"."transaction_category" add constraint "transaction_category_pkey" PRIMARY KEY using index "transaction_category_pkey";

grant delete on table "public"."transaction_category" to "anon";

grant insert on table "public"."transaction_category" to "anon";

grant references on table "public"."transaction_category" to "anon";

grant select on table "public"."transaction_category" to "anon";

grant trigger on table "public"."transaction_category" to "anon";

grant truncate on table "public"."transaction_category" to "anon";

grant update on table "public"."transaction_category" to "anon";

grant delete on table "public"."transaction_category" to "authenticated";

grant insert on table "public"."transaction_category" to "authenticated";

grant references on table "public"."transaction_category" to "authenticated";

grant select on table "public"."transaction_category" to "authenticated";

grant trigger on table "public"."transaction_category" to "authenticated";

grant truncate on table "public"."transaction_category" to "authenticated";

grant update on table "public"."transaction_category" to "authenticated";

grant delete on table "public"."transaction_category" to "service_role";

grant insert on table "public"."transaction_category" to "service_role";

grant references on table "public"."transaction_category" to "service_role";

grant select on table "public"."transaction_category" to "service_role";

grant trigger on table "public"."transaction_category" to "service_role";

grant truncate on table "public"."transaction_category" to "service_role";

grant update on table "public"."transaction_category" to "service_role";


