INSERT INTO transaction_category (id, name, display_name, emoji) VALUES
-- Incoming Categories
(1, 'earned income', 'Earned Income', '💵'),
(2, 'investment income and withdrawals', 'Investment Income And Withdrawals', '📈'),
(3, 'refunds and reimbursements', 'Refunds And Reimbursements', '🔙'),
(4, 'transfers in', 'Transfers In', '➡️'),
(5, 'loans and advances received', 'Loans And Advances Received', '💳'),
(6, 'misc income', 'Misc Income', '❓'),
(7, 'cash deposits', 'Cash Deposits', '🏦'),
(9, 'other incoming', 'Other Incoming', '🔍'),
-- Outgoing Categories
(10, 'housing', 'Housing', '🏠'),
(11, 'transportation', 'Transportation', '🚗'),
(12, 'groceries', 'Groceries', '🛒'),
(13, 'food and dining out', 'Food And Dining Out', '🍽️'),
(14, 'shopping and goods', 'Shopping And Goods', '🛍️'),
(15, 'entertainment and recreation', 'Entertainment And Recreation', '🎭'),
(16, 'health and wellness', 'Health And Wellness', '❤️'),
(17, 'personal care and services', 'Personal Care And Services', '🧖'),
(18, 'subscriptions and digital services', 'Subscriptions And Digital Services', '🖥️'),
(19, 'debt and loan payments', 'Debt And Loan Payments', '📉'),
(20, 'investments and savings', 'Investments And Savings', '💰'),
(21, 'insurance', 'Insurance', '🛡️'),
(22, 'taxes and government fees', 'Taxes And Government Fees', '🏛️'),
(23, 'travel', 'Travel', '✈️'),
(24, 'fees and charges', 'Fees And Charges', '⚠️'),
(25, 'gifts and donations', 'Gifts And Donations', '🎁'),
(26, 'cash withdrawals', 'Cash Withdrawals', '🏧'),
(27, 'transfers out', 'Transfers Out', '⬅️'),
(28, 'education', 'Education', '🎓'),
(30, 'other outgoing', 'Other Outgoing', '🔍');