INSERT INTO transaction_category (id, name, display_name, emoji) VALUES
(1, 'transfer from investment app', 'Transfer From Investment App', '💰'),
(2, 'transfer from stock broker', 'Transfer From Stock Broker', '📈'),
(3, 'transfer from crypto broker', 'Transfer From Crypto Broker', '🪙'),
(4, 'chargeback', 'Chargeback', '🔄'),
(5, 'freelance income', 'Freelance Income', '💼'),
(6, 'rideshare or delivery income', 'Rideshare Or Delivery Income', '🚗'),
(7, 'paycheck', 'Paycheck', '💵'),
(8, 'benefits', 'Benefits', '🎁'),
(9, 'interest earned', 'Interest Earned', '📊'),
(10, 'stock dividend', 'Stock Dividend', '📉'),
(11, 'property rental income', 'Property Rental Income', '🏠'),
(12, 'ATM deposit', 'ATM Deposit', '🏧'),
(13, 'teller deposit', 'Teller Deposit', '🏦'),
(14, 'adjustment', 'Adjustment', '⚖️'),
(15, 'inter account transfer', 'Inter Account Transfer', '🔀'),
(16, 'intra account transfer', 'Intra Account Transfer', '🔁'),
(17, 'peer to peer transfer', 'Peer To Peer Transfer', '🤝'),
(18, 'loan disbursement', 'Loan Disbursement', '💳'),
(19, 'cash advance', 'Cash Advance', '💸'),
(20, 'pawn loan', 'Pawn Loan', '💍'),
(21, 'cashback', 'Cashback', '💵'),
(22, 'insurance payout', 'Insurance Payout', '🛡️'),
(23, 'refund', 'Refund', '🔙'),
(24, 'tax refund', 'Tax Refund', '💰'),
(25, 'reversal', 'Reversal', '🔄'),
(26, 'gambling income', 'Gambling Income', '🎲'),
(27, 'grant or stipend', 'Grant Or Stipend', '🎓'),
(28, 'remittance', 'Remittance', '💌'),
(29, 'other', 'Other', '🔍'),
(30, 'prenote', 'Prenote', '📜'),
(31, 'missing account holder information', 'Missing Account Holder Information', '❓'),
(32, 'not enough information', 'Not Enough Information', '⚠️'),
(33, 'digital content and streaming', 'Digital Content And Streaming', '🎥'),
(34, 'vending machine', 'Vending Machine', '🛒'),
(35, 'reversal', 'Reversal', '🔄'),
(36, 'transfer to investment app', 'Transfer To Investment App', '💰'),
(37, 'transfer to stock broker', 'Transfer To Stock Broker', '📈'),
(38, 'transfer to crypto broker', 'Transfer To Crypto Broker', '🪙'),
(39, 'adjustment', 'Adjustment', '⚖️'),
(40, 'intra account transfer', 'Intra Account Transfer', '🔁'),
(41, 'inter account transfer', 'Inter Account Transfer', '🔀'),
(42, 'peer to peer transfer', 'Peer To Peer Transfer', '🤝'),
(43, 'funeral service', 'Funeral Service', '⚰️'),
(44, 'ATM withdrawal', 'ATM Withdrawal', '🏧'),
(45, 'teller withdrawal', 'Teller Withdrawal', '🏦'),
(46, 'bank fee', 'Bank Fee', '💳'),
(47, 'donation', 'Donation', '🎗️'),
(48, 'buy now, pay later', 'Buy Now, Pay Later', '🛍️'),
(49, 'pawn redeem', 'Pawn Redeem', '💍'),
(50, 'rent-to-own', 'Rent-To-Own', '🏠'),
(51, 'coffee shop', 'Coffee Shop', '☕'),
(52, 'liquor', 'Liquor', '🍷'),
(53, 'books, newsletters, newspapers', 'Books, Newsletters, Newspapers', '📚'),
(54, 'entertainment', 'Entertainment', '🎭'),
(55, 'gambling spend', 'Gambling Spend', '🎲'),
(56, 'sport and fitness', 'Sport And Fitness', '🏋️'),
(57, 'recreational goods', 'Recreational Goods', '🎣'),
(58, 'laundry', 'Laundry', '🧺'),
(59, 'clothing', 'Clothing', '👗'),
(60, 'convenience store', 'Convenience Store', '🛍️'),
(61, 'department or discount store', 'Department Or Discount Store', '🏬'),
(62, 'e-commerce purchase', 'E-Commerce Purchase', '🛒'),
(63, 'electronics', 'Electronics', '📱'),
(64, 'firearms', 'Firearms', '🔫'),
(65, 'home maintenance', 'Home Maintenance', '🔧'),
(66, 'legal services', 'Legal Services', '⚖️'),
(67, 'self care', 'Self Care', '🧖'),
(68, 'saas tools', 'SaaS Tools', '🖥️'),
(69, 'towing charge', 'Towing Charge', '🚗'),
(70, 'airfare', 'Airfare', '✈️'),
(71, 'hotel or lodging', 'Hotel Or Lodging', '🏨'),
(72, 'other transport', 'Other Transport', '🚙'),
(73, 'public transport', 'Public Transport', '🚌'),
(74, 'toll charge', 'Toll Charge', '💳'),
(75, 'overdraft fee', 'Overdraft Fee', '⚠️'),
(76, 'contribution to reserve fund', 'Contribution To Reserve Fund', '💰'),
(77, 'retirement contribution', 'Retirement Contribution', '👵'),
(78, 'credit card bill', 'Credit Card Bill', '💳'),
(79, 'debt collection', 'Debt Collection', '📉'),
(80, 'interest payment', 'Interest Payment', '💵'),
(81, 'mortgage repayment', 'Mortgage Repayment', '🏠'),
(82, 'student loan repayment', 'Student Loan Repayment', '🎓'),
(83, 'loan repayment', 'Loan Repayment', '💳'),
(84, 'cash advance repayment', 'Cash Advance Repayment', '💸'),
(85, 'auto loan repayment', 'Auto Loan Repayment', '🚗'),
(86, 'education', 'Education', '📚'),
(87, 'credit report', 'Credit Report', '📊'),
(88, 'groceries', 'Groceries', '🛒'),
(89, 'fast food', 'Fast Food', '🍔'),
(90, 'food delivery', 'Food Delivery', '🍕'),
(91, 'restaurant', 'Restaurant', '🍽️'),
(92, 'government', 'Government', '🏛️'),
(93, 'taxes', 'Taxes', '💰'),
(94, 'drugstore or pharmacy', 'Drugstore Or Pharmacy', '💊'),
(95, 'medical bill', 'Medical Bill', '🏥'),
(96, 'insurance premium', 'Insurance Premium', '🛡️'),
(97, 'bars and nightclubs', 'Bars And Nightclubs', '🍸'),
(98, 'auto lease payment', 'Auto Lease Payment', '🚗'),
(99, 'rent', 'Rent', '🏠'),
(100, 'childcare', 'Childcare', '👶'),
(101, 'pets', 'Pets', '🐾'),
(102, 'utilities', 'Utilities', '💡'),
(103, 'rideshare or taxi transport', 'Rideshare Or Taxi Transport', '🚖'),
(104, 'ev charging', 'EV Charging', '🔌'),
(105, 'fuel', 'Fuel', '⛽'),
(106, 'vehicle maintenance', 'Vehicle Maintenance', '🔧'),
(107, 'remittance', 'Remittance', '💌'),
(108, 'other', 'Other', '🔍'),
(109, 'prenote', 'Prenote', '📜'),
(110, 'missing account holder information', 'Missing Account Holder Information', '❓'),
(111, 'not enough information', 'Not Enough Information', '⚠️');