create table "public"."account_connection" (
    "id" bigint generated by default as identity not null,
    "institution_connection" bigint not null,
    "account_id" character varying not null
);


alter table "public"."account" drop column "initialized";

CREATE UNIQUE INDEX account_connection_pkey ON public.account_connection USING btree (id);

alter table "public"."account_connection" add constraint "account_connection_pkey" PRIMARY KEY using index "account_connection_pkey";

alter table "public"."account" add constraint "account_currency_fkey" FOREIGN KEY (currency) REFERENCES currency(code) not valid;

alter table "public"."account" validate constraint "account_currency_fkey";

alter table "public"."account_connection" add constraint "account_connection_institution_connection_fkey" FOREIGN KEY (institution_connection) REFERENCES institution_connection(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."account_connection" validate constraint "account_connection_institution_connection_fkey";

grant delete on table "public"."account_connection" to "anon";

grant insert on table "public"."account_connection" to "anon";

grant references on table "public"."account_connection" to "anon";

grant select on table "public"."account_connection" to "anon";

grant trigger on table "public"."account_connection" to "anon";

grant truncate on table "public"."account_connection" to "anon";

grant update on table "public"."account_connection" to "anon";

grant delete on table "public"."account_connection" to "authenticated";

grant insert on table "public"."account_connection" to "authenticated";

grant references on table "public"."account_connection" to "authenticated";

grant select on table "public"."account_connection" to "authenticated";

grant trigger on table "public"."account_connection" to "authenticated";

grant truncate on table "public"."account_connection" to "authenticated";

grant update on table "public"."account_connection" to "authenticated";

grant delete on table "public"."account_connection" to "service_role";

grant insert on table "public"."account_connection" to "service_role";

grant references on table "public"."account_connection" to "service_role";

grant select on table "public"."account_connection" to "service_role";

grant trigger on table "public"."account_connection" to "service_role";

grant truncate on table "public"."account_connection" to "service_role";

grant update on table "public"."account_connection" to "service_role";


