create table "public"."currency" (
    "id" bigint generated by default as identity not null,
    "code" text not null,
    "name" text not null,
    "country" character varying not null
);


CREATE UNIQUE INDEX currencies_pkey ON public.currency USING btree (id);

CREATE UNIQUE INDEX currency_code_key ON public.currency USING btree (code);

alter table "public"."currency" add constraint "currencies_pkey" PRIMARY KEY using index "currencies_pkey";

alter table "public"."currency" add constraint "currency_code_key" UNIQUE using index "currency_code_key";

grant delete on table "public"."currency" to "anon";

grant insert on table "public"."currency" to "anon";

grant references on table "public"."currency" to "anon";

grant select on table "public"."currency" to "anon";

grant trigger on table "public"."currency" to "anon";

grant truncate on table "public"."currency" to "anon";

grant update on table "public"."currency" to "anon";

grant delete on table "public"."currency" to "authenticated";

grant insert on table "public"."currency" to "authenticated";

grant references on table "public"."currency" to "authenticated";

grant select on table "public"."currency" to "authenticated";

grant trigger on table "public"."currency" to "authenticated";

grant truncate on table "public"."currency" to "authenticated";

grant update on table "public"."currency" to "authenticated";

grant delete on table "public"."currency" to "service_role";

grant insert on table "public"."currency" to "service_role";

grant references on table "public"."currency" to "service_role";

grant select on table "public"."currency" to "service_role";

grant trigger on table "public"."currency" to "service_role";

grant truncate on table "public"."currency" to "service_role";

grant update on table "public"."currency" to "service_role";


