alter table "public"."account" drop constraint "account_account_connection_id_institution_connection_id_fkey";

alter table "public"."account_connection" drop constraint "account_connection_pkey";

drop index if exists "public"."account_connection_pkey";

alter table "public"."account" drop column "institution_connection_id";

alter table "public"."account" alter column "account_connection_id" set data type bigint using "account_connection_id"::bigint;

alter table "public"."account_connection" add column "id" bigint generated by default as identity not null;

CREATE UNIQUE INDEX account_connection_pkey ON public.account_connection USING btree (id);

alter table "public"."account_connection" add constraint "account_connection_pkey" PRIMARY KEY using index "account_connection_pkey";

alter table "public"."account" add constraint "account_account_connection_id_fkey" FOREIGN KEY (account_connection_id) REFERENCES account_connection(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."account" validate constraint "account_account_connection_id_fkey";


