alter table "public"."institution_connection" drop constraint "institution_connection_provider_id_fkey";

alter table "public"."institution_connection" drop constraint "institution_connection_user_id_fkey";

alter table "public"."provider_connection" drop constraint "provider_connection_pkey";

drop index if exists "public"."provider_connection_pkey";

alter table "public"."institution_connection" drop column "provider_id";

alter table "public"."institution_connection" drop column "user_id";

alter table "public"."institution_connection" add column "provider_connection_id" bigint;

alter table "public"."provider_connection" add column "id" bigint generated by default as identity not null;

CREATE UNIQUE INDEX provider_connection_id_key ON public.provider_connection USING btree (id);

CREATE UNIQUE INDEX provider_connection_pkey ON public.provider_connection USING btree (id);

alter table "public"."provider_connection" add constraint "provider_connection_pkey" PRIMARY KEY using index "provider_connection_pkey";

alter table "public"."institution_connection" add constraint "institution_connection_provider_connection_id_fkey" FOREIGN KEY (provider_connection_id) REFERENCES provider_connection(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."institution_connection" validate constraint "institution_connection_provider_connection_id_fkey";

alter table "public"."provider_connection" add constraint "provider_connection_id_key" UNIQUE using index "provider_connection_id_key";


