#:schema node_modules/wrangler/config-schema.json
name = "guilders-api"
main = "src/app.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]
routes = [
  { pattern = "api.guilders.app", custom_domain = true }
]
assets = { directory = "public" }
upload_source_maps = true

kv_namespaces = [
  { binding = "KV", id = "75f194b1b1144673bd6e2cb72a6a90ba" },
  { binding = "ENRICH_KV", id = "8454847e04d04933a2b8e0e01c4952de" }
]

[dev]
port = 3002

[triggers]
crons = ["0 * * * *", "0 0 * * *", "0 */6 * * *"]

[observability]
enabled = true