#:schema node_modules/wrangler/config-schema.json
name = "guilders-api"
main = "src/app.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]
routes = [
  { pattern = "api.guilders.app", custom_domain = true }
]

[dev]
port = 3002

[triggers]
crons = ["0 * * * *", "0 0 * * *"]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true