#:schema node_modules/wrangler/config-schema.json
name = "guilders-api"
main = "src/app.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]
routes = [
  { pattern = "api.guilders.app", custom_domain = true }
]

[dev]
port = 3002

[triggers]
crons = ["0 * * * *", "0 0 * * *"]

[observability]
enabled = true

[env.local.vars]
API_URL = "https://badly-mutual-pigeon.ngrok-free.app"

[env.production.vars]
API_URL = "https://api.guilders.app"
